export const SLIDES = [
  {
    id: "s0",
    number: "00",
    label: "Title",
    heading: "UE-Guard: Lightweight Hybrid Misbehavior Detection of False Base Station Attacks on UE",
    time: "~30s",
    subtitle:
      "A Three-Layer Hybrid Framework Using Specification-Based Rules and Probabilistic Anomaly Scoring",
    authors: "Vincent Abella",
    venue: "MobiSec Winter Seminar 2026",
  },
  {
    id: "s1",
    number: "01",
    label: "Agenda",
    heading: "Agenda",
    time: "~30s",
    items: [
      "Background & Problem Statement",
      "Attack Vectors in Cellular Networks",
      "Limitations of Existing Approaches",
      "UE-Guard System Architecture",
      "Layer 1: Specification-Based Rules (BR-1–14) & Formal Verification",
      "Layer 2: Probabilistic Anomaly Scoring",
      "Layer 3: Adaptive Threshold Manager",
      "Evaluation: Dataset, Accuracy & Efficiency",
      "Why Hybrid: Complementary Strengths",
      "Conclusion & Future Work",
    ],
  },
  {
    id: "s2",
    number: "02",
    label: "Background",
    heading: "Cellular Networks Have a Trust Problem",
    time: "~1:30",
    bullets: [
      {
        main: "Modern cellular networks (4G LTE, 5G) rely on asymmetric authentication",
        sub: ["The network authenticates the UE", "The UE does not authenticate the base station"],
      },
      {
        main: "This gap enables False Base Station (FBS) attacks",
        sub: ["Rogue stations impersonating legitimate towers"],
      },
      {
        main: "Attackers exploit this to:",
        sub: [
          "Track subscriber identity (IMSI catching)",
          "Eavesdrop via security downgrade",
          "Deny service by forcing disconnection",
          "Manipulate UE behavior through illegitimate signaling",
        ],
      },
    ],
  },
  {
    id: "s3",
    number: "03",
    label: "Attack Vectors",
    heading: "Eight Categories of False Base Station Attacks",
    time: "~1:30",
    table: [
      { category: "Identity Catching", example: "Identity Request (IMSI/IMEI) before auth, or IMSI in paging, enables subscriber tracking (IMSI catcher)", phase: "NAS" },
      { category: "Security Downgrade", example: "Security Mode with null cipher (EEA0) or null integrity (EIA0) exposes traffic to eavesdropping", phase: "NAS" },
      { category: "State Manipulation", example: "RRC reestablish/reconfig flooding, spurious paging, or invalid state transitions cause DoS or hijacking", phase: "RRC" },
      { category: "Service Rejection", example: "RRC/NAS Reject without integrity forces de-registration and denial of service", phase: "RRC/NAS" },
      { category: "Location Tracking", example: "TAU or service request when UE already registered enables location or activity inference", phase: "NAS" },
      { category: "Network Downgrade", example: "SIB advertises 2G/3G-only, so UE falls back to less secure generation (bidding-down)", phase: "RRC" },
      { category: "Resource Depletion", example: "Mass connection requests or PRACH abuse cause battery drain and degraded responsiveness", phase: "PRACH/RRC" },
      { category: "Protocol Failures", example: "Auth failure/reject, sync loss, or unexpected reject indicates MITM or rogue base station", phase: "NAS" },
    ],
  },
  {
    id: "s4",
    number: "04",
    label: "Limitations",
    heading: "Why Existing Detection Falls Short",
    time: "~1:00",
    table: [
      { approach: "Network-centric detection", limitation: "UE is blind to its own attacks. Privacy concerns" },
      { approach: "Pure ML (LSTM, CNN, GRU)", limitation: "High memory, high latency, black-box decisions" },
      { approach: "Signature-based only", limitation: "Misses novel/zero-day attack patterns" },
      { approach: "Static threshold methods", limitation: "Not adaptive to deployment environments" },
    ],
    keyGap:
      "No existing solution combines standards-grounded correctness, probabilistic generalization, and edge-device efficiency",
  },
  {
    id: "s5",
    number: "05",
    label: "System Architecture",
    heading: "System Architecture",
    time: "~1:00",
    pipeline: [
      "PCAP Capture → PDML Parser → Field Extractor",
      "Layer 1: Specification → Behavior Rule Violations (BR-1–14)",
      "Layer 2: Probabilistic → Anomaly Score ∈ [0, 1]",
      "Layer 3: Threshold Mgr → Final Decision: Attack / Normal",
    ],
    designPhase: "Rules derived from 3GPP specs and security threats, formally verified (UPPAAL) and empirically calibrated.",
    runtimePhase: "RRC/NAS traffic is monitored, preprocessed, and evaluated by three layers to produce a compliance decision.",
    layer1: "Deterministic rules detect known protocol violations (BR-1–14).",
    layer2: "Probabilistic scoring identifies anomalous transitions and field values.",
    layer3: "Adaptive threshold yields the final attack/normal classification.",
  },
  {
    id: "s6",
    number: "06",
    label: "Layer 1",
    heading: "Layer 1 — Deterministic Behavior Rules from 3GPP Standards",
    time: "~2:00",
    source: "8 3GPP Technical Specifications: TS 24.301, TS 24.501, TS 33.401, TS 33.501, TS 36.331, TS 38.331, TS 36.304, TS 38.304",
    rules: [
      "Identify protocol invariants",
      "Extract normative clauses with 'shall' / 'shall not'",
      "Implement unified detection logic for LTE and 5G",
      "Map each rule to a threat category",
    ],
    output: "14 Behavior Rules: BR-1–7 (RRC), BR-8–14 (NAS). Binary violation flag per rule.",
  },
  {
    id: "s7",
    number: "07",
    label: "Behavior Rules",
    heading: "Behavior Rules — RRC and NAS Coverage",
    time: "~1:30",
    rrcRules: [
      { id: "BR-1", desc: "RRC state transition flooding" },
      { id: "BR-2", desc: "SIB inconsistency — cell ID spoofing" },
      { id: "BR-3", desc: "Unsolicited paging with IMSI/SUPI" },
      { id: "BR-4", desc: "Invalid cell barring signals" },
      { id: "BR-5", desc: "RRC connection rate limiting (DoS)" },
      { id: "BR-6", desc: "Abnormal RRC release/reject patterns" },
      { id: "BR-7", desc: "Null encryption or null integrity" },
    ],
    nasRules: [
      { id: "BR-8", desc: "Attach/registration procedure violations" },
      { id: "BR-9", desc: "Authentication procedure anomalies" },
      { id: "BR-10", desc: "Identity request outside valid context (IMSI catcher)" },
      { id: "BR-11", desc: "NAS message integrity failures" },
      { id: "BR-12", desc: "TAU/service request violations" },
      { id: "BR-13", desc: "Reject messages without integrity protection" },
      { id: "BR-14", desc: "Unsolicited network-initiated detach" },
    ],
  },
  {
    id: "s7b",
    number: "08",
    label: "Behavior Rules (Fig. 4)",
    heading: "Layer 1 Detection Framework — Complete Overview",
    figureCaption: "Layer 1 specification-based behavior rules (BR-1 to BR-14) with RRC/NAS state machine context, 3GPP specification alignment, security requirements, threat categories, and detection logic.",
  },
  {
    id: "s8",
    number: "09",
    label: "Formal Verification",
    heading: "Formal Verification — Methodology",
    time: "~0:45",
    methodology: "Layer 1 (Specification-Based Behavior Rules) is modeled as a network of timed automata in UPPAAL.",
  },
  {
    id: "s8b",
    number: "10",
    label: "Formal Verification",
    heading: "Formal Verification — Detection_Agent",
    time: "~0:45",
    detectionAgent: "Monitors UE messages against BR-1–14. Attack State Indicator (ASI) tracks violations with a bitwise system (BR-1: bit 0 … BR-14: bit 13). Each checkBRxx() evaluates protocol conditions and sets ASI |= 2^x on violation.",
  },
  {
    id: "s8c",
    number: "11",
    label: "Formal Verification",
    heading: "Formal Verification — Checker",
    time: "~0:45",
    checker: "Validates Detection_Agent decisions. No_error: correct attack detection. Error: false positive or false negative. Parameterized by BR mask, reaches No_error when (ASI & mask) == mask.",
  },
  {
    id: "s8d",
    number: "12",
    label: "Formal Verification",
    heading: "Formal Verification — Verification Results",
    time: "~0:30",
    results: [
      { property: "Completeness", query: "Reachability", count: 14, result: "✓ All pass" },
      { property: "Correctness", query: "Invariant", count: 14, result: "✓ All pass" },
      { property: "Safety", query: "Safety", count: 1, result: "✓ Pass" },
    ],
    total: "29/29 queries verified successfully",
  },
  {
    id: "s9",
    number: "13",
    label: "Layer 2",
    heading: "Layer 2 — First-Order Markov Chain Anomaly Scoring",
    time: "~2:00",
    goal: "Learn transition probabilities from normal traffic, then score new messages by rarity (common → low score, rare → high score).",
    steps: [
      {
        step: 1,
        title: "State representation",
        desc: "A state combines network, protocol with direction, and message type.",
        stateExamples: [
          { network: "5G", protocolDirection: "rrc downlink", messageType: "Attach request" },
          { network: "LTE", protocolDirection: "nas uplink", messageType: "Security mode complete" },
        ],
      },
      { step: 2, title: "Training", desc: "Use normal traffic to count how often each transition occurs. Compute the probability of the next state given the current one." },
      { step: 3, title: "Scoring", desc: "For each new message, look up its transition probability. Rarer transitions get higher anomaly scores. Formula on next slide." },
    ],
    trainingResult: "7 normal samples → 26 states, 55 transitions, P ∈ [0.014, 1.0]",
  },
  {
    id: "s10",
    number: "14",
    label: "Layer 2",
    heading: "Layer 2 — Information-Theoretic Surprise Scoring",
    time: "~1:30",
    intro: "Each transition gets a score based on how surprising (rare) it is under the learned model. Lower probability means higher anomaly score. Scores use normalized self-information (surprisal), which Shannon information theory defines as -log₂(P).",
    formula: "score = -log₂(P) / max_surprise",
    formulaNote: "max_surprise is the largest observed surprise across learned transitions, normalizing scores to [0, 1]",
    scoreTable: [
      { scenario: "Common transition (high P, e.g. 0.9)", score: "~0.15" },
      { scenario: "Rare transition (low P, e.g. 0.01)", score: "~0.66" },
      { scenario: "Unseen transition to known state", score: "0.90" },
      { scenario: "Unknown state entirely", score: "1.00" },
    ],
    rarityTable: [
      {
        type: "Transition rarity",
        weight: "70%",
        desc: "Scores how surprising the state change is under the learned model. Rare transitions yield higher scores.",
        example: ["AttachRequest → IdentityRequest", "SecurityModeCommand → RegistrationReject"],
      },
      {
        type: "Field value rarity",
        weight: "30%",
        desc: "Scores how unusual the protocol parameter values are given learned value distributions from normal traffic.",
        example: ["Cause code", "Ciphering algorithm", "Release cause in a message"],
      },
    ],
    combined: "Per-row score = 0.7 × transition_score + 0.3 × field_score. Behavioral patterns weigh more than parameter values.",
  },
  {
    id: "s11",
    number: "15",
    label: "Layer 3",
    heading: "Layer 3 — Minimally Adaptive Decision Boundary",
    time: "~1:00",
    purpose: "Learns the optimal anomaly threshold from labeled data to maximize accuracy. Only this threshold is adaptive. Other parameters stay fixed for stability.",
    threshold: "0.2858",
    decision: [
      "if (any_behavior_rule_violated)",
      "  → ANOMALOUS  // Layer 1 override",
      "else if (anomaly_score >= θ_anomaly)",
      "  → ANOMALOUS  // Layer 2 detection",
      "else",
      "  → NORMAL",
    ],
  },
  {
    id: "s12",
    number: "16",
    label: "Dataset",
    heading: "Evaluation Dataset — 51 Samples, 17,096 Protocol Messages",
    time: "~1:00",
    table: [
      { category: "State Manipulation", samples: 13, examples: "RRC flooding, paging attacks" },
      { category: "Encryption/Security", samples: 9, examples: "Null cipher downgrade" },
      { category: "Service Rejection", samples: 7, examples: "Malicious reject messages" },
      { category: "Network Downgrade", samples: 4, examples: "Bidding-down" },
      { category: "Location Tracking", samples: 3, examples: "Unauthorized TAU" },
      { category: "Identity Catching", samples: 3, examples: "IMSI/IMEI exfiltration" },
      { category: "Resource Depletion", samples: 3, examples: "Connection flooding" },
      { category: "Protocol Failures", samples: 2, examples: "Auth failure, sync loss" },
      { category: "Normal", samples: 7, examples: "Real network captures" },
    ],
    pipeline: "PCAP → Wireshark PDML → XML parser → 67 RRC/NAS fields → CSV",
  },
  {
    id: "s13",
    number: "17",
    label: "Results",
    heading: "Detection Accuracy Across All 51 Samples",
    time: "~1:30",
    resultsTable: [
      { system: "UE-Guard", accuracy: "100.00%", tp: 44, tn: 7, fp: 0, fn: 0, tpr: "100.00%", tnr: "100.00%", fpr: "0.00%" },
      { system: "LSTM", accuracy: "92.16%", tp: 41, tn: 6, fp: 1, fn: 3, tpr: "93.18%", tnr: "85.71%", fpr: "14.29%" },
      { system: "GRU", accuracy: "88.24%", tp: 40, tn: 5, fp: 2, fn: 4, tpr: "90.91%", tnr: "71.43%", fpr: "28.57%" },
      { system: "CNN", accuracy: "82.35%", tp: 38, tn: 4, fp: 3, fn: 6, tpr: "86.36%", tnr: "57.14%", fpr: "42.86%" },
    ],
    separation: "Score separation: Normal 0.098–0.247 | Attack 0.325–0.653 | No overlap → θ = 0.2858. Same 51 samples (44 attack, 7 normal), identical features.",
  },
  {
    id: "s14",
    number: "18",
    label: "Efficiency",
    heading: "Computational Performance Benchmark (Per-File Average)",
    time: "~1:00",
    performanceTable: [
      { approach: "LSTM", preprocess: "886.86", detection: "875.73", total: "1762.59", memory: "86.75" },
      { approach: "GRU", preprocess: "886.86", detection: "737.70", total: "1624.56", memory: "86.75" },
      { approach: "CNN", preprocess: "886.86", detection: "374.87", total: "1261.73", memory: "86.75" },
      { approach: "UE-Guard (Proposed)", preprocess: "616.41", detection: "19.10", total: "635.51", memory: "0.22", system: "UE-Guard" },
      { approach: "↳ Layer 1 (Spec-Based)", preprocess: "—", detection: "7.42", total: "—", memory: "0.03" },
      { approach: "↳ Layer 2 (Probabilistic)", preprocess: "—", detection: "11.68", total: "—", memory: "0.19" },
    ],
    noteBullets: [
      { label: "Environment", value: "51 samples · Docker (4 GB RAM, 2 cores) · Python 3.12" },
      { label: "Detection speed", value: "45.8× vs LSTM · 38.6× vs GRU · 19.6× vs CNN" },
      { label: "Memory", value: "394× smaller than deep learning models" },
      { label: "Per-message", value: "Layer 1 ≈ 0.022 ms · Layer 2 ≈ 0.035 ms" },
      { label: "Scalability", value: "O(n) linear · 26–2,396 packets per sample" },
    ],
  },
  {
    id: "s15",
    number: "19",
    label: "Why Hybrid",
    heading: "Specification + Probabilistic = Complementary Strengths",
    time: "~1:00",
    table: [
      { dim: "Detection type", l1: "Known protocol violations", l2: "Novel / subtle anomalies" },
      { dim: "Basis", l1: "3GPP standards", l2: "Statistical patterns" },
      { dim: "Output", l1: "Binary (violation / no violation)", l2: "Continuous score [0, 1]" },
      { dim: "Formal guarantee", l1: "Yes (UPPAAL verified)", l2: "No" },
      { dim: "Coverage", l1: "Specification-defined attacks", l2: "Out-of-distribution behavior" },
    ],
    together: "Deterministic coverage of known attacks + probabilistic generalization to novel patterns",
  },
  {
    id: "s16",
    number: "20",
    label: "Conclusion",
    heading: "Conclusion & Future Work",
    time: "~1:00",
    contributions: [
      "Lightweight hybrid framework for 4G/5G edge devices (mobile, IoT, IoMT)",
      "Layer 1: 14 specification rules (BR-1–14) — UPPAAL formal verification, 29/29 queries pass",
      "Layer 2: Probabilistic anomaly scoring with information-theoretic surprise",
      "Layer 3: Adaptive threshold calibration (θ = 0.2858) from labeled data",
      "51 samples (44 attack, 7 normal): 100% accuracy, 19.10 ms detection, 0.22 MB memory",
      "45.8× faster than LSTM, 394× smaller than deep learning models",
      "Explainable detections traceable to 3GPP specifications",
    ],
    future: [
      { area: "Deployment", items: ["Mobile devices (Qualcomm QXDM battery assessment)", "Cellular IoT sensors", "IoMT medical devices"] },
      { area: "Dataset expansion", items: ["Normal traffic from diverse operators and device types", "Sophisticated attack samples (evasion, signature reshaping)", "Production network environments"] },
      { area: "Layer 2 enhancements", items: ["Online adaptation", "Cross-layer correlation with physical layer (signal strength, timing advance)"] },
    ],
  },
];
